# This is a basic workflow to help you get started with Actions

name: CI with Pact contracts test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      pactConsumerTags:
        description: pact tags separated by comma
        default: ''
        required: false


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    env:
      PACT_CONSUMER_TAGS:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: setup-env-variables-from-inputs
        if: ${{ github.event.inputs.pactConsumerTags != '' }}
        run: echo "${{ github.event.inputs.pactConsumerTags }}" >> $PACT_CONSUMER_TAGS
      - name: setup-env-variables
        if: ${{ github.event.inputs == '' }}
        run: echo "$GITHUB_REF,test" >> $PACT_CONSUMER_TAGS
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: build
        run: ./mvnw clean package -Dpact.consumer.tags=$PACT_CONSUMER_TAGS
      - name: publish pacts
        run: ./mvnw pact:publish -Dpact.consumer.tags=$PACT_CONSUMER_TAGS